apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: consistent-aardwolf-go 
  janus-idp.io/tekton: consistent-aardwolf-go
  backstage.io/kubernetes-id: consistent-aardwolf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: consistent-aardwolf-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  