apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: consistent-aardwolf-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: consistent-aardwolf-go 
  name: consistent-aardwolf-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: consistent-aardwolf-go
    weight: 100 
