apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: consistent-aardwolf-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: consistent-aardwolf-go 
  name: consistent-aardwolf-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: consistent-aardwolf-go 
